food = input("taco")
name = input("Audrey")
adjective = input("disappointed")
noun = input("shoelace")
noun2 = input("eye")
verb1 = input("backflipped")
verb2 = input("cartwheeled")
verb3 = input("burpeed")
print("It was {food} day at school, and {name} was super {adjective} for lunch. But when she went outside to eat, a {noun} stole her {food}! {name} chased the {noun} all over the school. She {verb1}, {verb2}, and {verb3} all over the playground. Then she tripped on her {noun2} and the {noun} escaped! Luckily, {name}'s friends were willing to share their {food} with her.")
